config/routes.rb
Rails.application.routes.draw do
  resources :parents_baby_names
  resources :babies
  resources :teams
  resources :baby_names

  resources :parents do 
    resources :baby_names
  end

  get 'google', to: redirect('/auth/google_oauth2')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  get 'login', to: "sessions#login"
  post 'login', to: "sessions#create"
  get 'sign_up', to: "sessions#new"
  post 'sign_up', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  get '/', to: "sessions#home", as: 'home'
  # get '/:anything', to: "application#wrong_page"
  
  # root to: "home#show"
end

app/models/parent.rb
class Parent < ApplicationRecord    
    belongs_to :team
    belongs_to :baby
    has_many :parents_baby_names
    has_many :baby_names, through: :parents_baby_names
   
    def add_baby_name_to_list(parent, baby_name)
        if parent.baby_names.length < 10 
            parent.baby_names << baby_name
        else
            flash[:alert] = "Your list is full"
        end
    end
    
    def baby_names_attributes=(baby_name_attributes)
        baby_name_attributes.values.each do |baby_name_attribute|
            baby_name = BabyName.find_or_create_by(baby_name_attribute)
            #self.baby_names.find_or_create_by(baby_name.name)
            unless self.baby_names.exists?(baby_name.id) 
                self.baby_names << baby_name
            end
        end
    end

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
    before_action :set_team, only: [:index, :show, :update]
    before_action :set_parent, only: [:show, :update]
    
    def index    
        @parents = current_team.parents        
    end
    
    def show
        session[:parent_id] = @parent.id
        @baby_names = BabyName.all

        if params[:baby_name_id]
            @baby_name = BabyName.find_by_id(params[:baby_name_id])
            @parent.add_baby_name_to_list(@parent, @baby_name)
        end 
        10.times {@baby_name = @parent.baby_names.build}  
    end

    def update 
            @baby_names = BabyName.all 
            @parent.parents_baby_names.destroy_all
            @parent.update(parent_params)
        
        if @parent.save
            render :show
        else
            render :index
        end
    end

    private

    def parent_params
        params.require(:parent).permit( :name, :roll, baby_names_attributes: [:name])
    end

    def set_parent 
        @parent = Parent.find_by_id(params[:id]) 
    end

    def set_team
        @team = current_team
    end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/index.erb
<div class="errors-font">

<% if current_team.errors.any? %>
  <br><br><%= current_team.errors.full_messages.to_sentence %>
<% end %>

</div>

<br><br><br>
<div class="question-box">
    <h6>Who are you?</h6><br>
</div>
<br>
<% @parents.each do |parent| %>
    <% if parent.roll == "Daddy"%>
        <h2 style="color:lightblue"><%=link_to "Papa #{parent.name}", parent_path(parent) %></h2><br>
    <% elsif parent.roll == "Mommy" %>
        <h2 style="color:lightpink"><%=link_to "Mama #{parent.name}", parent_path(parent) %></h2><br>
    <% else %>
        <h2 style="color:yellow"><%=link_to parent.name, parent_path(parent) %></h2><br>
    <% end %>
<% end %>
<br><br><br>

app/views/parents/show.erb
<div class="errors-font">

<% if current_team.errors.any? %>
  <br><br><%= current_team.errors.full_messages.to_sentence %>
<% end %>

</div>

<%= form_tag parent_baby_name_path(current_parent), :method => "get" do %> 
    <%= text_field_tag :name, params[:name], placeholder: "Find a name", list: "baby_names_autocomplete"  %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist><br><br>
    <%= submit_tag("  Name info  ", :class => "button2", :name => nil) %>
        
    <% end %>
    <br><br><%= link_to "Baby names directory", parent_baby_names_path(current_parent), class: "button2", method: "get"%> 
    

    <div class="info">

    <% if parent_logged_in? %>

        <% if current_parent.roll == "Daddy" %>
		    <h5 style="color:lightblue">Papa <%= current_parent.name %>'s Top Picks:</h5>
	    <% elsif current_parent.roll == "Mommy"%>
		    <h5 style="color:lightpink">Mama <%= current_parent.name %>'s Top Picks:</h5>
	    <% else %>
		    <h5 style="color:yellow"><%= current_parent.name %>'s Top Picks:</h5>
	    <% end %>
    <% end %> <br><b>

    <%= form_with model: @parent do |f| %>
    <%= f.fields_for :baby_names, @parent.baby_names[0] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist>            
    <% end %>

    <%= f.fields_for :baby_names, @parent.baby_names[1] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist><br><br>            
    <% end %>

    <%= f.fields_for :baby_names, @parent.baby_names[2] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist>            
    <% end %>

    <%= f.fields_for :baby_names, @parent.baby_names[3] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist><br><br>            
    <% end %>

    <%= f.fields_for :baby_names, @parent.baby_names[4] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist>           
    <% end %>

    <%= f.fields_for :baby_names, @parent.baby_names[5] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist><br><br>            
    <% end %>

    <%= f.fields_for :baby_names, @parent.baby_names[6] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist>          
    <% end %>

    <%= f.fields_for :baby_names, @parent.baby_names[7] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>

        </datalist><br><br>            
    <% end %>
    <%= f.fields_for :baby_names, @parent.baby_names[8] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist>

    <% end %>
    <%= f.fields_for :baby_names, @parent.baby_names[9] do |b| %>
        <%= b.text_field :name, list: "baby_names_autocomplete" %>
        <datalist id="baby_names_autocomplete">
            <% BabyName.all.each do |baby_name| %>
                <option value="<%= baby_name.name %>">
            <% end %>
        </datalist><br><br>            
    <% end %>

    <%= f.submit "Save my list!", :class => "button2" %><br><br><br><br>
    </div>
<% end %>
				