config/routes.rb
Rails.application.routes.draw do
  resources :parents_baby_names
  resources :babies
  resources :teams
  resources :baby_names

  resources :parents do 
    resources :baby_names
  end

  get 'google', to: redirect('/auth/google_oauth2')
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  
  get 'login', to: "sessions#login"
  post 'login', to: "sessions#create"
  get 'sign_up', to: "sessions#new"
  post 'sign_up', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"

  get '/', to: "sessions#home", as: 'home'
  # get '/:anything', to: "application#wrong_page"
  
  # root to: "home#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<body class="background--<%=baby_gender%>">
	


  	<head>
	  
    	<title>LetsNameTheBaby</title>
    	<%= csrf_meta_tags %>
    	<%= csp_meta_tag %>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=0.7"/>
    	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= favicon_link_tag asset_path('baby.png') %>
		<meta
      name="description"
      content="Let's Name the Baby"
    />
    <meta name="title" property="og:title" content="Let's Name the Baby" />
    <meta property="og:type" content="Website" />
    <meta name="image" property="og:image" content="https://live.staticflickr.com/65535/50993355931_568fd0862e_b.jpg" />
    <meta name="description" property="og:description" content="Baby naming app" />
    <meta name="author" content="Adam Workman" />

  	</head>
	  
  	<div class="blur">
		

        <section class="babynameapp">
			<header class="header">
			<% if parent_logged_in? %>
				<h4>Team:</h4>
			<% end %>

			<% if team_logged_in? %>
				<h1 <% if baby_gender == "Boy" %>
						style="color:lightblue"
					<% elsif baby_gender == "Girl" %>
						style="color:lightpink"
					<% else %>
						style="color:yellow"
					<% end %>>

					<%= current_team.teamname  %></h1>
			<% end %>

			

			</header>
			
        
			<section class="main" style="display: block;">
			<div class="info">

    <%= yield %>
	</section>
			<footer class="footer" style="display: block;">
			<% if parent_logged_in?%>
				<ul class="filters">
					<li>
						<%= link_to "Update Team", edit_team_path(current_team), :method => "get" %>
					</li>
					<li>
						<%= link_to "My List", parent_path(current_parent), :method => "get" %>	
					</li>
					<li>
						<%= link_to "Show Matching Names", team_path(current_team) %>
					</li>
					<li>
                        <%= link_to "Log Out", logout_path, method: "delete" %>
					</li>
				</ul>
			<% elsif team_logged_in? && current_team.password_digest %>				
				<ul class="filters">
					<li>
						<%= link_to "Home", home_path, :method => "get" %>	
					</li>
					<% if team_logged_in? %>
					<li>
                        <%= link_to "Log Out", logout_path, method: "delete" %>
					</li>
					<li>
						<%= link_to "Update Team", edit_team_path(current_team), :method => "get" %>
					</li>
					<% end %>				
				</ul>
			<% else %>
				<ul class="filters">
					<li>
						<%= link_to "Sign In", login_path, :method => "get" %>
					</li>
					<li>
						<%= link_to "Home", home_path, :method => "get" %>	
					</li>
					<li>
						<%= link_to "Sign Up", sign_up_path, :method => "get" %>
					</li>
				</ul>
			<% end %>

			</footer>
		</section>
  	</div>
	</body>	
</html>

app/views/layouts/home.erb
<!DOCTYPE html>

<html>
    <body class="background--<%=baby_gender%>">
  	<head>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=0.7"/>
      <meta name="google-site-verification" content="1x6QDN0aBXXKgOE2JkwpU_sQt5XUCa5bt0blF-y0tP4" />
      <meta
      name="description"
      content="Let's Name the Baby"
    />
    <meta name="title" property="og:title" content="Let's Name the Baby" />
    <meta property="og:type" content="Website" />
    <meta name="image" property="og:image" content="https://live.staticflickr.com/65535/50993355931_568fd0862e_b.jpg" />
    <meta name="description" property="og:description" content="Baby naming app" />
    <meta name="author" content="Adam Workman" />
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script>
                $(function(){    
                    setTimeout(function(){ 
                            $('.button2').fadeIn();
                    }, 500);
                });
            </script>
	  
    	<title>LetsNameTheBaby</title>
    	<%= csrf_meta_tags %>
    	<%= csp_meta_tag %>

    	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%= favicon_link_tag asset_path('baby.png') %>
  	</head>
      
  	<div>
		<div class="home-box">      

    <%= yield %>
    
        </div>
    <div>	
  	</body>  	
</html>